Fixing issues, upgrade dependency and version
eventB-Soton/CODA_VHDL pull request #9
Opened 2018-11-06 11:47 UTC by tshoang

The following improvements are made:
- Added some spacing around WHEN clause. This closes #7.
- Used .vhd extension instead of .vhdl. This closes #8.
- Used vhdl built-in types: boolean and integer. This closes #5.

2019-01-08 16:27 UTC, cfsnook requested changes
in vhdl.generator manifest - Bundle-RequiredExecutionEnvironment: JavaSE-1.8 (also in tests?)
in vhdl.generator manifest - use 'compatible' version range for dependencies
in vhdl.edit manifest - do not re-export dependencies

2019-01-08 16:27 UTC, cfsnook commented on ac.soton.coda.vhdl.generator/META-INF/MANIFEST.MF
> + ac.soton.eventb.emf.decomposition;bundle-version="0.1.0"
give a compatible version range

2019-01-08 16:30 UTC, cfsnook reviewed
documentation still needs updating re BOOL?

2019-01-08 16:32 UTC, cfsnook requested changes
".vhdl" is still used in two places in vhdl generator plugin

2019-01-08 16:44 UTC, tshoang commented
Do you know where  ".vhdl" is used in the generator? Searching the source does not help as it also in the plugin's name. The documentation need to be updated, but it was generated from the Utils repository and the generation script need to be fixed.

2019-01-08 17:15 UTC, cfsnook commented
creating output files in
 ac.soton.coda.internal.eventB2vxmi.EventB2VXMIUtils.generate(..)
&
ac.soton.coda.internal.vhdl.utils.VHDLTestBenchGeneratorUtils.generate(..)

n.b. I searched for "".vhdl""

2019-01-08 17:22 UTC, tshoang commented
Thanks, I see. That is for generating test bench which should be updated to generate VXMI instead of VHDL code directly. I changed the extension anyway.

2019-01-10 12:43 UTC, cfsnook commented
These don't seem to have been addressed:
in vhdl.generator manifest - Bundle-RequiredExecutionEnvironment: JavaSE-1.8 (also in tests?)
in vhdl.edit manifest - do not re-export dependencies

2019-01-17 16:03 UTC, cfsnook approved these changes

2019-01-17 19:28 UTC, merged